# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
