# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0003_auto_20170609_0856'),
        ('archive', '0003_strain_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='owners',
        ),
        migrations.AddField(
            model_name='strain',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Organisation'),
        ),
        migrations.AddField(
            model_name='strain',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
