# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0004_auto_20170609_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='owner',
        ),
        migrations.AddField(
            model_name='strain',
            name='purchasers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strain',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
