# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20170609_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='uploader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
