# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0006_auto_20170609_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='purchasers',
        ),
        migrations.AddField(
            model_name='strain',
            name='purchasers',
            field=models.ManyToManyField(null=True, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
