# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20170609_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='purchasers',
            new_name='purchases',
        ),
    ]
