# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20170609_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='data_url',
            field=models.URLField(null=True),
        ),
    ]
