# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_strain_data_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='purchases',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='uploader',
        ),
        migrations.AddField(
            model_name='strain',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
