# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20170614_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='family',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='genus',
        ),
    ]
