# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20170614_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Family'),
        ),
        migrations.AddField(
            model_name='strain',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Genus'),
        ),
    ]
