# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20170614_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
