# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_strain_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='organisation',
        ),
    ]
