# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_remove_strain_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='family',
        ),
        migrations.RemoveField(
            model_name='species',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='family',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='species',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Genus',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
