# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_auto_20170712_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=1000)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('iso_alpha_2', models.CharField(blank=True, max_length=2)),
                ('iso_num', models.CharField(blank=True, max_length=3)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='strain',
            name='strain_type',
        ),
        migrations.AddField(
            model_name='strain',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strain',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='environmental_sample_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='strain',
            name='host_taxon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='host_taxon_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='strain',
            name='taxon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='taxon_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='strain',
            name='collection_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Location'),
        ),
    ]
