# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_strain_data_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_auto_20170612_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archive.Strain')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_strains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Strain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
