# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170612_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Strain'),
        ),
    ]
