# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170612_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='strain',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='selected_strains',
        ),
        migrations.AddField(
            model_name='quote',
            name='body',
            field=models.TextField(default='BLANK'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
