# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_auto_20170612_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='body',
        ),
        migrations.AddField(
            model_name='quote',
            name='basket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.ConfirmedBasket'),
        ),
    ]
