# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_strain_data_url'),
        ('cart', '0006_auto_20170612_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Strain')),
            ],
        ),
        migrations.AddField(
            model_name='confirmedbasket',
            name='purchases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Purchase'),
        ),
    ]
