# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20170612_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Processing'), ('D', 'Dispatched'), ('R', 'Received'), ('V', 'Void')], default='P', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Quote'),
        ),
    ]
