# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20170612_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='sent',
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('A', 'Accepted'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
    ]
