# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20170612_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedbasket',
            name='purchases',
        ),
        migrations.AddField(
            model_name='confirmedbasket',
            name='purchases',
            field=models.ManyToManyField(null=True, to='cart.Purchase'),
        ),
    ]
