# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20170612_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedbasket',
            name='purchases',
            field=models.ManyToManyField(to='cart.Purchase'),
        ),
    ]
