# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20170612_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Awaiting Payment'), ('P', 'Processing'), ('D', 'Dispatched'), ('R', 'Received'), ('V', 'Void')], default='A', max_length=1),
        ),
    ]
