# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20170613_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='confirmedbasket',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='funding_type',
            field=models.CharField(default='NS', max_length=2),
        ),
    ]
