# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20170622_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='custoer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
