# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_quote_custoer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='custoer_name',
            new_name='customer_name',
        ),
    ]
