# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20170622_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedbasket',
            name='user',
        ),
    ]
