# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_confirmedbasket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
