# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20170622_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_date',
            field=models.DateTimeField(null=True),
        ),
    ]
