# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20170622_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='funding_type',
            field=models.CharField(choices=[('NC', 'Non-Commercial'), ('B', 'BBSRC'), ('I', 'Industry'), ('UB', 'Internal UoB'), ('NS', 'Not Set')], default='NS', max_length=2),
        ),
    ]
