# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20170626_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='max_usages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
