# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_auto_20170626_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='code',
            new_name='codes',
        ),
        migrations.AddField(
            model_name='promotion',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='number_of_uses',
            field=models.IntegerField(default=0),
        ),
    ]
