# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_promotion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
