# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_promotion_promotion_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('FP', 'Fixed Price Reduction'), ('PR', 'Percentage Reduction'), ('NS', 'Not Set')], default='NS', max_length=4),
        ),
    ]
