# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_promotion_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PO', 'Payment Order'), ('OS', 'Online Shop'), ('NS', 'Not Set')], default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('D', 'Dispatched'), ('R', 'Received'), ('V', 'Void')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('FPR', 'Fixed Price Reduction'), ('PPR', 'Percentage Reduction'), ('NS', 'Not Set')], default='NS', max_length=4),
        ),
    ]
