# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_auto_20170629_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PP', 'Pending Payment'), ('P', 'Processing'), ('AD', 'Awaiting Dispatch'), ('D', 'Dispatched'), ('R', 'Received'), ('V', 'Void')], default='PP', max_length=2),
        ),
    ]
