# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_auto_20170629_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cirms_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='finance_reference_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_order_reference_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_order_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_transaction_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
