# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_auto_20170629_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=30, null=True)),
                ('pdf', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, null=True)),
                ('transaction_number', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_order_reference_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_transaction_number',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.PaymentOrder'),
        ),
    ]
