# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_auto_20170629_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.ShopOrder'),
        ),
    ]
