# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_order_shop_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
