# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_auto_20170705_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedbasket',
            name='applied_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.PromotionCode'),
        ),
    ]
